SELECT * FROM customer LIMIT 20;

-- Q1. What is the total revenue generated by male vs female customers?

SELECT * FROM customer;

SELECT 
	gender,
	sum(purchased_amount) as revenue
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT * FROM customer;

SELECT customer_id, purchased_amount
FROM customer
WHERE discount_applied = 'Yes' and purchased_amount >=(SELECT AVG(purchased_amount) FROM customer)
ORDER BY purchased_amount;


--Q3. Which are the top 5 product with the highest average review rating?

select * from customer

SELECT item_purchased, ROUND(AVG(review_rating)::numeric,2) as average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT * FROM customer;

SELECT * 
FROM(
	SELECT shipping_type, ROUND(AVG(purchased_amount),2) as revenue
	FROM customer
	GROUP BY shipping_type
)
WHERE shipping_type = 'Standard' or shipping_type = 'Express';

-- Alternate Option

SELECT shipping_type, ROUND(AVG(purchased_amount),2) AS revenue
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.


SELECT * FROM customer;

SELECT 
	subscription_status,
	COUNT(customer_id) AS total_customer,
	ROUND(AVG(purchased_amount),2)AS average_spend,
	SUM(purchased_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY subscription_status desc;



-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT * FROM customer;

SELECT
	item_purchased AS product,
	COUNT(*) as total_purchases,
	SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
	ROUND(
		SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)::numeric,
	2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and
--	   show the count of each segment.

SELECT * FROM customer;

WITH customer_type AS (
	SELECT customer_id, previous_purchases,
		CASE 
			WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
		END AS customer_segment
	FROM customer
)
SELECT customer_segment, COUNT(customer_id) AS number_od_customer,SUM(previous_purchases) revenue
FROM customer_type
GROUP BY customer_segment

-- Q8. What are the top 3 most purchased products within each category

SELECT * FROM customer


WITH item_counts AS (
	SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
		   ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
	FROM customer
	GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also like to subscribe?

SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?

SELECT * FROM customer;

SELECT age_group, SUM(purchased_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;


